title: "Headers"
description: |
  This page contains the headers used across all the website pages.

patterns:
  header-main:
    title: "Main Header"
    description: |
      This header is to be used on the main page only and is already supplied in the front layout.
  header-sec:
    title: "Inside Header"
    description: |
      This header is to be used on all inside pages only and is already supplied in the inside layout.
