title: "Cards"
description: |
  Cards are used to describe important bits of information quickly on the website.

patterns:
  product-card:
    title: "Product Card"
    description: |
      This is the standard product card. It should always contain an image, title, product title and a price.
    width: 400
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  sale-card:
    title: "Sale Card"
    description: |
      This is a sale card and used when an item goes on sale. Must contain an image, title, product title, original price and a the current sale price.
    width: 400
  promo-card:
    title: "Promotion Card"
    description: |
      This is a typical promo card that features new content. It is to be used on the home page as a sectional piece and can be used up to four times in a row for other products or promotions currently being offered. It should include a image, title and link to the promoted area.
    width: 400
  icon-card:
    title: "Icon Card"
    description: |
      The Icon Card is used to display quick information on different aspects of the company. This includes where its made, shipping, returns etc. and a learn more option for the user to click on. Four of these cards will be located on the front page at the very bottom just above the footer.
    width: 400
