title: "Cards"
description: |
  Cards are used to describe important bits of information quickly on the website.

patterns:
  product-card:
    title: "product card"
    description: |
      hello
    width: 400

  sale-card:
    width: 400
