title: "Sections"
description: |
  These sections are to be used on the main page. They will contain information involving new items, deals and art work that the site will provide for future circumstances.

patterns:
  sectional-banner:
    title: "Sectional Banner"
    description: |
      The sectional banner is used to promote new items or events that the website will offer. It should be used on the front page as a section and contains a larger image to support the width. and the product must be located on the left side of the image.
    fields:
      - name: heading
        type: string
        example: "Brand new mugs starting at 20% off!"
      - name: desc
        type: string
        example: "Get them now, deal only lasts till February 12th"
      - name: image
        type: url
        example: "/images/section-example.jpg"
      - name: aria_label
        type: string
        example: "This is an image of the new Catonaut ceramic mug"
  half-section:
    title: "Half Section"
    description: |
      The half sections are used when the image is not a full banner and are only found on the front page. It also uses an outlined button so that it brings more attention.
    fields:
      - name: heading
        type: string
        example: "Brand new mugs starting at 20% off!"
      - name: desc
        type: string
        example: "Get them now, deal only lasts till February 12th"
      - name: image
        type: url
        example: "/images/products/product-catonaut-mug.jpg"
      - name: aria_label
        type: string
        example: "This is an image of the new Catonaut ceramic mug"
      - name: button_text
        type: string
        example: "Learn More"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
      - name: button_aria
        type: string
        example: "This link will lead you somewhere"
        required: false
  text-sec:
    title: "Text Section"
    description: |
      This text section can be used for multiple lines of text. It is typically used for describing things such an about us or other things relating to the sites content. It can inculde a regular button but no imagery, but bear in mind that it would not be good for promoting items.
    fields:
      - name: title
        type: string
        example: "About Us"
      - name: text
        type: string
        example: "Catonaut is for the internet who loves cats and love products with cats on them even more! No one loves our little feline friends more than us. So start your crazy cat collection today with all of this beautiful art."
  image-sec:
    title: "Image Section"
    description: |
      The image section is used as seperator of content and can be filled with any image needed. It contains no text or buttons and is stricly meant for seperating purposes.
    fields:
      - name: url
        type: string
        example: "/images/banners/cat-banner.jpg"
      - name: aria_label
        type: string
        example: "Out anjoying the sun."
