title: "Banners"
description: |
  Banners are to be used sparingly as they can be higher resolution images.

patterns:
  hero-banner:
    title: "Call to Action"
    description: |
      The call to action banner should only be used on the front store page and only ever used with a search bar. It is a means for the user to search the website.
    fields:
      - name: heading
        type: string
        example: "Rocket ship ready and fueled"
      - name: banner
        type: string
        example: "banner-example.jpg"
  promo-banner:
    title: "Promtional Banner"
    description: |
      The promotional banner is used to promote current deals and sales that the site has to offer, but can be found on every page at the top. This is allowed because it can never have an image with it.
    fields:
      - name: heading
        type: string
        example: "All mugs are now 20% off!"
      - name: description
        type: string
        example: "Get it now, offer only lasts till February 12th"
      - name: url
        type: string
        example: "#"
  page-banner:
    title: "Page Banner"
    description: |
      A Page banner is used for seperpate pages on the website, they do not include an image. They can include a button though. If it has a button the pattern code must include the button_text and button_url.
    fields:
      - name: heading
        type: string
        example: "All Products"
      - name: button_text
        type: string
        example: "Learn More"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
  img-banner:
    title: "Image Banner"
    description: |
      The image banner can be included on any page that is not the front page or the product related page. This can include about us page, updates page etc.
    fields:
      - name: title
        type: string
        example: "About Us"
      - name: desc
        type: string
        example: "The Puurfect site for every cat lover."
      - name: url
        type: string
        example: "/images/banners/banner-example.jpg"
